menu:
  Home: /
  Archives: /archives
  About: /about

widgets: 
- recent_posts
- tagcloud 

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false

fancybox: true

google_analytics: UA-50169885-1
domain: hugofeng.info
rss: 

